import junit.framework.*;
/*
 * NewTestSuite.java
 * JUnit based test
 *
 * Created on July 15, 2007, 8:51 PM
 */

/**
 *
 * @author wgrover
 */
public class NewTestSuite extends TestCase {
    
    public NewTestSuite(String testName) {
        super(testName);
    }

    protected void setUp() throws Exception {
    }

    protected void tearDown() throws Exception {
    }

    /**
     * suite method automatically generated by JUnit module
     */
    public static Test suite() {
        TestSuite suite = new TestSuite("NewTestSuite");
        return suite;
    }
    
}
